### ISSUE TITLE
[Spelling] Several in 2 paragraphs.

### ISSUE THREAD

**Issue by challsted** [delayel06/youarethehero#12]
You continue to stay at your original pace. You observe how the sun's setting light rests on the trees and the shrubs around you. A few scurrying mice pass by right below your feet, as well as a chicken, crossing the road right in front of you.

Wagons pass by, each carrying their specific load of supplies, even some empty. It would mean a lot to you to have a **responsability** **sometihn** to do. You realize that your life has no meaning right now, that you aren't doing anything.
However, you are grateful that you're not **emprisoned** by the grasp of some jobs and responsibilities, like most people are. You want to find balance in your life, a perfect equilibrium that will become your reason to live, your sole existence.

While thinking about all the new thoughts surging to your brain, you get lost. The road abruptly ended, and now you have no idea where to go.

**Comment by delayel06** [comment]
Ah, so many spelling errors I have yet to fix. Thank you for your feedback, with every patch I fix more

**Comment by challsted** [comment]
Thanks for the quick replies! 

Feel free to close all these spelling issues i created as you feel they should be.
