### ISSUE TITLE
Can't leave potion vendor

### ISSUE THREAD

**Issue by chipmccormick** [delayel06/youarethehero#3]
The only options are to buy one of the two potions for sale. Other vendors have a leave option

**Comment by delayel06** [comment]
That shouldn't be possible, as the things you can buy are based on your class..
`Welcome to the weapon shop!

Here are the choices for your class:
(if: $class is 1)[
[[Steel Sword]] (+1 damage) -- 200 gold
[[Metal Shield]] (+1 defense) -- 100 gold
]
(elseif: $class is 2)[
[[Arcane Staff]] (+1 damage) -- 200 gold
[[Ward spell]] (+1 defense) -- 100 gold
]
(elseif: $class is 3)[
[[Bronze daggers]] (+1.5 damage) -- 150 gold
]

[[Leave.]] `

This is the code I have for the first weapon vendor.. `1` is warrior, `2` is wizard and `3` is thief.

What I think may have happened is that the "I don't really know what I am" isn't switching well to other class types.
Is that the character you used?

**Comment by challsted** [comment]
This issueeems to be fixed, can we close this?
