### ISSUE TITLE
Error on Page

### ISSUE THREAD

**Issue by challsted** [delayel06/youarethehero#6]
"The Else command should be assigned to a variable or attached to a hook."

Not sure what info you need.
I chose theif, i just escaped a prison, i chose to pull a leaver which leaked asid on to skin and i ran "Outside!" Then i seen that error on screen. I took a screenshot but havnt uploaded it anywhere. If you need it let me know.

**Comment by challsted** [comment]
YouAreTheHero Error https://imgur.com/gallery/HZ90s

Here you go, image.

**Comment by delayel06** [comment]
Thanks a lot.  I forgot an extra bracket(hook) during a variable of the game. Thanks you for the picture as well, it helped nicely.

**Comment by challsted** [comment]
Feel free to close this when ever you feel like you have corrected it :) if i see more i can open more issues. 

Fun game sofar :)
