### ISSUE TITLE
Taking damage less than defence heals the hero

### ISSUE THREAD

**Issue by thefryscorer** [delayel06/youarethehero#7]
As the title. With a defence score of 3.5, a bear hitting the hero for 2 damage has the effect of healing the hero by 1.5 points. This seems like unintended behaviour.

This was with a fighter hero, wearing leather armour.

**Comment by delayel06** [comment]
This problem I had before, but I thought I fixed it.
For the basic overview, I am using [id defense is more than enemy attack, then...] I don't put anything after then as it should just not do anything.

Thank you though. I will try to fix it.
